# Generated by Django 5.1.7 on 2025-04-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("knowledge_graph", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgegraph",
            name="topics",
            field=models.ManyToManyField(
                related_name="knowledge_graphs",
                through="knowledge_graph.GraphEdge",
                to="core.topic",
            ),
        ),
    ]
