version: '3.8'

services:
  web:
    build:
      context: .
    image: pal_backend:latest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - model-data:/app/models
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: postgres:15
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=pal_user
      - POSTGRES_PASSWORD=pal_password
      - POSTGRES_DB=pal_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped

  celery:
    image: pal_backend:latest
    command: celery -A pal_project worker -l INFO
    volumes:
      - .:/app
      - model-data:/app/models
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped

  celery-beat:
    image: pal_backend:latest
    command: celery -A pal_project beat -l INFO
    volumes:
      - .:/app
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env
    restart: unless-stopped

volumes:
  postgres-data:
  model-data:
