# Generated by Django 5.1.7 on 2025-05-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="estimated_time",
            field=models.DurationField(
                blank=True, help_text="Estimated time to complete resource", null=True
            ),
        ),
    ]
