# Generated by Django 5.1.7 on 2025-05-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_resource_estimated_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("document", "Document"),
                    ("exercise", "Exercise"),
                    ("tutorial", "Tutorial"),
                    ("quiz", "Quiz"),
                    ("example", "Example"),
                    ("reference", "Reference"),
                    ("documentation", "Documentation"),
                    ("course", "Course"),
                    ("book", "Book"),
                    ("practice", "Practice"),
                ],
                max_length=20,
            ),
        ),
    ]
