# Generated by Django 5.1.7 on 2025-06-18 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_resource_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple Choice"),
                    ("coding", "Coding"),
                    ("code_analysis", "Code Analysis"),
                    ("fill_blank", "Fill in the Blank"),
                    ("short_answer", "Short Answer"),
                    ("essay", "Essay"),
                    ("true_false", "True/False"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("document", "Document"),
                    ("exercise", "Exercise"),
                    ("tutorial", "Tutorial"),
                    ("quiz", "Quiz"),
                    ("example", "Example"),
                    ("reference", "Reference"),
                    ("documentation", "Documentation"),
                    ("course", "Course"),
                    ("book", "Book"),
                    ("practice", "Practice"),
                    ("video", "Video"),
                    ("documentation", "Documentation"),
                    ("visual", "Visual"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
