# Generated by Django 5.1.7 on 2025-04-07 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data_ingestion",
            "0002_alter_processinglog_data_upload_documentupload_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="extractedquestion",
            options={"ordering": ["document", "question_number"]},
        ),
        migrations.AddField(
            model_name="extractedquestion",
            name="validation_metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
