# Generated by Django 5.1.7 on 2025-04-24 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_ingestion", "0003_alter_extractedquestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataupload",
            name="error_file",
            field=models.FileField(blank=True, null=True, upload_to="error_reports/"),
        ),
    ]
