# Generated by Django 5.1.7 on 2025-04-02 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeTracingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("dkt", "Deep Knowledge Tracing"),
                            ("sakt", "Self-Attentive Knowledge Tracing"),
                            ("custom", "Custom Model"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_path", models.CharField(max_length=255)),
                ("hyperparameters", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("training", "Training"),
                            ("active", "Active"),
                            ("failed", "Failed"),
                            ("archived", "Archived"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_models",
                        to="core.course",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PredictionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_students", models.IntegerField(default=0)),
                ("processed_students", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prediction_batches",
                        to="ml_models.knowledgetracingmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("hyperparameters", models.JSONField(default=dict)),
                ("metrics", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("total_students", models.IntegerField(default=0)),
                ("total_interactions", models.IntegerField(default=0)),
                (
                    "split_ratio",
                    models.FloatField(default=0.8, help_text="Train/test split ratio"),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_jobs",
                        to="ml_models.knowledgetracingmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TopicMastery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mastery_score",
                    models.FloatField(help_text="Mastery score between 0 and 1"),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Confidence in the prediction between 0 and 1"
                    ),
                ),
                ("predicted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("declining", "Declining"),
                            ("stagnant", "Stagnant"),
                        ],
                        default="stagnant",
                        max_length=20,
                    ),
                ),
                (
                    "trend_data",
                    models.JSONField(
                        default=list, help_text="Historical mastery scores"
                    ),
                ),
                (
                    "prediction_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="ml_models.predictionbatch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_masteries",
                        to="core.student",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_masteries",
                        to="core.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-predicted_at"],
                "unique_together": {("student", "topic", "prediction_batch")},
            },
        ),
    ]
