# Generated by Django 5.1.7 on 2025-04-02 03:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("knowledge_graph", "0001_initial"),
        ("ml_models", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("overall_progress", models.JSONField(default=dict)),
                (
                    "estimated_completion_time",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to="core.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_paths",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningPathItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("weak", "Weak"),
                            ("developing", "Developing"),
                            ("strong", "Strong"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "proficiency_score",
                    models.FloatField(help_text="Mastery score between 0 and 1"),
                ),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("declining", "Declining"),
                            ("stagnant", "Stagnant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_of_improvement",
                    models.FloatField(
                        help_text="Confidence in improvement prediction between 0 and 1"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Explanation for why this topic is in the path"
                    ),
                ),
                (
                    "estimated_review_time",
                    models.DurationField(
                        help_text="Estimated time to review this topic"
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="learning_paths.learningpath",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_items",
                        to="core.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["path", "priority"],
                "unique_together": {("path", "topic")},
            },
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_reason",
                    models.TextField(
                        help_text="Reason why this resource is recommended"
                    ),
                ),
                ("viewed", models.BooleanField(default=False)),
                ("viewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "path_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="learning_paths.learningpathitem",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_recommendations",
                        to="core.resource",
                    ),
                ),
            ],
            options={
                "ordering": ["path_item"],
            },
        ),
        migrations.CreateModel(
            name="PathCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "checkpoint_type",
                    models.CharField(
                        choices=[
                            ("quiz", "Quiz"),
                            ("exercise", "Exercise"),
                            ("reflection", "Reflection"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "position",
                    models.IntegerField(help_text="Position in the learning path"),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                (
                    "path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="learning_paths.learningpath",
                    ),
                ),
                (
                    "topics",
                    models.ManyToManyField(related_name="checkpoints", to="core.topic"),
                ),
            ],
            options={
                "ordering": ["path", "position"],
            },
        ),
        migrations.CreateModel(
            name="PathGenerationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_generation_jobs",
                        to="core.course",
                    ),
                ),
                (
                    "knowledge_graph",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="path_generation_jobs",
                        to="knowledge_graph.knowledgegraph",
                    ),
                ),
                (
                    "prediction_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="path_generation_jobs",
                        to="ml_models.predictionbatch",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="path_generation_jobs",
                        to="core.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="learningpath",
            name="generation_job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="path",
                to="learning_paths.pathgenerationjob",
            ),
        ),
        migrations.CreateModel(
            name="PathGenerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Configuration parameters for the generator",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="pathgenerationjob",
            name="generator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="learning_paths.pathgenerator",
            ),
        ),
    ]
